### PR TITLE
Introduce illuminate/collections

### PR DESCRIPTION
**Pull request by szepeviktor**
as `Tightenco\Collect` is over: https://github.com/tighten/collect/blob/laravel-8-ongoing/readme.md#collect---illuminate-collections

### CODE REVIEW

**Comment by joelambert** [comment]
I like this but would constitute a change so we may want to consider adding in an alias for `Tightenco\Collect\Support\Collection` => `Illuminate\Support\Collection`.

That way we can choose to deprecate the Tightenco namespace at a later date.

**Comment by szepeviktor** [comment]
Okay! `class_alias()` is not an OOP creature. How to do it?

**Comment by joelambert** [comment]
We probably want something like this from the Tighten package, where we include the file in the `composer.json` autoloader:

https://github.com/tighten/collect/blob/laravel-8-ongoing/src/Collect/Support/alias.php

But the other way around. I think it would be worth putting a test around this too to make sure that we can use either namespace using the Illuminate package.

**Comment by joelambert** [comment]
This is unfortunately a little more involved than just switching packages, work has begun to solve this here https://github.com/Rareloop/lumberjack-core/pull/40

**Pull request closed without merging**
