### PR TITLE
Add PHP 8 support

### PR DESCRIPTION
**Pull request by joelambert**
- [x] Upgrade to PHPUnit 9
- [x] Upgrade to php 8 compatible Router
- [x] Determine minimum Timber version for php 8 support
- [x] Update LJ core to support php8
- [x] Test inside WordPress
- [x] Wait until [new version of AltoRouter is released](https://github.com/Rareloop/router/pull/15) and bump min version of `rareloop/router` to include the fix

### CODE REVIEW

**Comment by joelambert** [comment]
Failing tests due to a PHP 8 issue with Timber.

Code has been patched but not yet released, see: https://github.com/timber/timber/issues/2450

**Comment by AjXUthaya** [comment]
Any new news regarding the support for PHP 8

**Comment by joelambert** [comment]
I've rolled back the commit to add PHP 8.1 as a test environment. There are a few other issues in 3rd party packages that we'll need to resolve before this becomes possible.

**Comment by JshGrn** [comment]
Hi! Great to see this, what is currently outstanding for support of at least PHP 8.0?

**Comment by JshGrn** [comment]
Hi, what is left to at least support PHP 8?

**Comment by trsteel88** [comment]
@joelambert would love to see this merged. Is there anything outstanding? Happy to help where I can.

**Comment by adamtomat** [comment]
@trsteel88 we just need to test this on some existing sites to make sure there are no issues. If you're able to do any testing and let us know if it's good / of any bugs that would be 👍 

We plan on doing some thorough testing in the next couple weeks too

**Comment by JshGrn** [comment]
I would be happy to run it for testing, I didn't know what was outstanding or not

**Review by adamtomat — APPROVED** [review]

**Pull request merged**
