### PR TITLE
Add PHP 8.1 support

### PR DESCRIPTION
**Pull request by joelambert**
Added support for PHP 8.1

**Breaking changes**
- Update namespace for Collections from `Tightenco\Collect\Support\Collection` to `Illuminate\Support\Collection`

### CODE REVIEW

**Comment by gido** [comment]
Hi @joelambert,

I'm interested in PHP 8.1 support. How can I help?

**Comment by joelambert** [comment]
> Hi @joelambert,
> 
> I'm interested in PHP 8.1 support. How can I help?

@gido it looks like the test are mostly passing, we may need to increase the minimum version of `Stringy` to get the last test to pass but that isn't too much work.

In addition to getting the tests passing we need to check that the new version of the framework actually works in a real 8.1 environment. Perhaps you could test that and see if you run into any issues? I would setup a fresh WordPress/Lumberjack install and then use this PR branch instead of the latest release in your `composer.json` file.

We've had reports that the Symphony package used for error handling might potentially cause issues on 8.1 so it would be useful to throw some Exceptions and check that that is working as expected.

**Comment by gido** [comment]
Thanks, I will do some test on current project with this branch and report the results.

**Comment by idflood** [comment]
Hi @joelambert ,

I quickly tested the 8.1 branch on a project and there are errors related to timber 1.x branch not supporting php 8.1. (see https://github.com/timber/timber/issues/2548)

So I believe lumberjack will have to use the 2.x dev version or a fork of timber 1.x (or make the 1.x branch support php 8.1 🤞)

**Comment by joelambert** [comment]
Thanks @idflood, this matches with our own findings too. I'm hoping that 8.1 fixes are pushed into Timber 1.x as I'm not sure when v2 is set for release and there are also quite a few breaking changes between the versions.

We're also considering allowing more control over the Lumberjack exception handler to be able to exclude certain errors on a site by site basis.

**Comment by gchtr** [comment]
> I'm hoping that 8.1 fixes are pushed into Timber 1.x as I'm not sure when v2 is set for release and there are also quite a few breaking changes between the versions.

@joelambert We’re on it. PHP 8 and 8.1 will be supported in Timber to ease the transition to v2 as soon as it’s released.

**Comment by joelambert** [comment]
@idflood are you able to test again now Timber has been updated?

**Comment by idflood** [comment]
@joelambert I quickly tested the updated branch and got two errors. I didn't try to dig deeper, but these might be related to local settings even though it's the most simple wordpress setup we have (and it works fine with php 8.0).

On frontend:

```
(1/1) ErrorException
setcookie(): Passing null to parameter #5 ($domain) of type string is deprecated
--
in SessionServiceProvider.php line 51
at RegisterExceptionHandler->handleError(8192, 'setcookie(): Passing null to parameter #5 ($domain) of type string is deprecated', '/var/www/vendor/rareloop/lumberjack-core/src/Providers/SessionServiceProvider.php', 51)
at setcookie('lumberjack_session', 'RcGyLyABXJCcyWHdMz5Y06eBL4Uy038oCyqNuXwD', 1667832028, '/', null, false, true)in SessionServiceProvider.php line 51
at SessionServiceProvider->Rareloop\Lumberjack\Providers\{closure}(object(WP))in class-wp-hook.php line 307
at WP_Hook->apply_filters('', array(object(WP)))in class-wp-hook.php line 331
at WP_Hook->do_action(array(object(WP)))in plugin.php line 524
at do_action_ref_array('send_headers', array(object(WP)))in class-wp.php line 546
at WP->send_headers()in class-wp.php line 772
at WP->main('')in functions.php line 1330
at wp()in wp-blog-header.php line 16
at require('/var/www/app/wp-blog-header.php')in index.php line 17
```

On wp-login:

```
(1/1) ErrorException
preg_replace(): Passing null to parameter #3 ($subject) of type array\|string is deprecated
--
in formatting.php line 5385
at RegisterExceptionHandler->handleError(8192, 'preg_replace(): Passing null to parameter #3 ($subject) of type array\|string is deprecated', '/var/www/app/wp-includes/formatting.php', 5385)
at preg_replace('@<(script\|style)[^>]*?>.*?</\\1>@si', '', null)in formatting.php line 5385
at wp_strip_all_tags(null)in formatting.php line 2115
at sanitize_user(null)in pluggable.php line 603
at wp_authenticate(null, null)in user.php line 95
at wp_signon(array('remember' => false, 'user_login' => null, 'user_password' => null), false)in wp-login.php line 1221
```

**Comment by joelambert** [comment]
@idflood thanks, I wasn't getting the first error but after a few refreshes I am now. We'll get this fixed.

We also think that we may need to tweak the way the exception handler reports errors to support all the new deprecation warnings that 8.1 throws.

**Comment by idflood** [comment]
@joelambert nice, I have no more errors on the frontend 👌

The backend has still a lot of deprecated warnings from the wordpress codebase even though I added this to my config/app.php . But this is maybe not directly related to this issue.

Also note that for now I only tested on a minimal website, I will try on a more realistic production website asap.

```
    'errors' => [
      'reportOnly' => [E_ERROR]
    ],
```

**Comment by idflood** [comment]
@joelambert Thanks for the infos. I just tested this branch on a real production website and it works nicely.

The numerous "Deprecated" warnings were in fact coming from the "EWWW Image Optimizer" plugin so they are not really related to this issue : )

**Comment by gido** [comment]
🙌 
I Forget to report that we use this branch on a productive website for a while and it's working as expected!

**Pull request merged**
