### PR TITLE
Explicitly add illuminate/support to composer dependencies

### PR DESCRIPTION
**Pull request by nlemoine**
What does this implement/fix? Explain your changes.
---------------------------------------------------

1. Lumberjack Core is using `illuminate/support` without explicitly declaring it in the `composer` dependencies (this argument should be self sufficient ;)).
2. I stumbled upon a very weird issue where Lumberjack causes errors with `wp-cli`. Try running this with the current dependencies (and PHP 7.3):

```php
(new Collection(['apple', 'banana', 'kiwi']))->first(function ($value, $key) {
    var_dump($value);
    var_dump($key);
});
```
For an unknown reason, in a browser, I get the `$value` as the value but on cli, value of `$value` is `$key` and `$key` contains the value... 

In Lumberjack, this was leading to a PHP error here: https://github.com/Rareloop/lumberjack-core/blob/a751f08996520b4975d72860876c39377e465004/src/Application.php#L187-L189

(`get_class` on `int`)

Does this close any currently open issues?
------------------------------------------

No.

### CODE REVIEW

**Comment by adamtomat** [comment]
@nlemoine Thanks for your PR!

We made a decision not to bring in the whole of `illuminate/support` as it contains a lot that we don't need. Instead, we use `tightenco/collect` (https://github.com/tightenco/collect) to just bring in the collection stuff.

Regarding your other issue, this looks like an issue with the version of the collection package that is being used. I know they swapped the order around of key and value at some point.

Have you brought in `illuminate/support` yourself? If so that may be causing a conflict.

**Comment by nlemoine** [comment]
Hi @adamtomat,

Thanks for the prompt reply!

I checked that package but you are still calling `illuminate/support`: https://github.com/Rareloop/lumberjack-core/blob/a751f08996520b4975d72860876c39377e465004/src/Application.php#L7

> Have you brought in illuminate/support yourself? If so that may be causing a conflict.

`composer req illuminate/support` solved the error and I didn't notice any conflict although I didn't check the whole package scope.

**Comment by nlemoine** [comment]
Whoops, I didn't see `tightenco/collect` had an alias file to map `illuminate/support` class names.

However, the bug is still here: 
```
[2020-01-28 17:19:37] app.ERROR: ErrorException: get_class() expects parameter 1 to be object, int given in path/vendor/rareloop/lumberjack-core/src/Application.php:188
```

**Comment by nlemoine** [comment]
Even with the latest version of `tightenco/collect`, I still get the error. I setup a standalone test case. `tightenco/collect` works fine both in browser and cli.

The issue seems to come from an somewhere else. Are you able to reproduce?

``` bash
lumberjack-bedrock new my-site
// install
wp post list
```

**Comment by nlemoine** [comment]
Just spotted the issue. It came from a wp-cli package (https://github.com/aaemnnosttv/wp-cli-dotenv-command) that is using an old version of `tightenco/collect`...

Sorry for the inconvenience, I PRed too fast.

The `tightenco/collect` update might still be relevant so I'll leave the PR opened. 

I'll probably come back later with other features/issues (cli error reporting prints HTML, DI container is using "dev" mode, etc.) I have in mind but I'll try my best to propose better PRs ;)

**Pull request closed without merging**
